---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[opsworks_ruby::setup]
      - recipe[opsworks_ruby::deploy]
    # no attributes at all, to prove that cookbook can work "out of the box"
    attributes:
